name: Licensed

on:
  push:
    branches:
      - test-update-licensed-tool
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-licensed:
    name: Licensed
    uses: priyagupta108/reusable-workflows/.github/workflows/licensed.yml@update-licensed-tool
